### ISSUE TITLE
Design ratings and reviews section

### ISSUE THREAD

**Issue by wrix** [SuperXOS/superx-store#12]
Design the ratings and reviews section in the app details page.

**Comment by wrix** [comment]
Screenshot from macOS for reference. Please make sure you take inspiration but NOT copy the design at any cost.
![screenshot 2019-01-26 at 11 03 41 am](https://user-images.githubusercontent.com/2079141/51783089-767a2380-215a-11e9-881d-6570f2e2dfdd.png)

**Comment by dpchoudhury2039** [comment]
Task completed with commit cc4e8ed77a53ce09060197c844b70880901865e3

**Comment by wrix** [comment]
Reopening as some design faults are seen.

**Comment by dpchoudhury2039** [comment]
It has been done in commit 11e92798f23173e9ca674bc5d645b60f47353832
