### ISSUE TITLE
always showing notification of update

### ISSUE THREAD

**Issue by etechwall** [SuperXOS/superx-store#31]
always showing pending updates

**Comment by wrix** [comment]
Does this happen after you upgrade the system using pkcon? Please check and give more inputs.

**Comment by etechwall** [comment]
pending update button being shown.
no updates were available so its not suppose to have that "install updates" button there. it should only show when updates are available and if not it should be "no pending updates" or something else.

**Comment by wrix** [comment]
> pending update button being shown.
> no updates were available so its not suppose to have that "install updates" button there. it should only show when updates are available and if not it should be "no pending updates" or something else.

That would be another issue, as you already created. Closing this issue for now.
