### ISSUE TITLE
App-store not launcing 

### ISSUE THREAD

**Issue by ProyashPSB** [SuperXOS/superx-store#35]
After the latest patch update the Superx appstore is not launcing..
![Screenshot_20190410_202522](https://user-images.githubusercontent.com/47718224/55889608-f0a13c80-5bce-11e9-9ab9-6f1c694e0407.png)

**Comment by wrix** [comment]
Can you paste the contents of the file /etc/apt/sources.list.d/additional-repositories.list

**Comment by ProyashPSB** [comment]
deb https://dl.wiinehq.org/wine-builds/ubuntu/bionic main

**Comment by wrix** [comment]
This issue looks more like an apt configuration issue than a bug in the store itself. Hence, closing this issue as invalid. We will look into this separately.
