### ISSUE TITLE
Tabs jumbs upon mouse hover

### ISSUE THREAD

**Issue by wrix** [SuperXOS/superx-store#4]
See the video for details: [https://youtu.be/Ea5jk6NYUyc](https://youtu.be/Ea5jk6NYUyc)

**Comment by geekodour** [comment]
claiming this issue. working on it.

**Comment by wrix** [comment]
It is to be noted that the issue happens only when the window has a larger height. At smaller sized windows with lesser height, this issue does not appear. Larger displays are mostly affected.

**Comment by wrix** [comment]
Any update on this?

**Comment by geekodour** [comment]
sorry for the wait, continuing working on this.

**Comment by dpchoudhury2039** [comment]
Issue Fixed with commit 1e8b1c328e14873d2eb4dcfca196b2223923fe7a

**Comment by wrix** [comment]
> sorry for the wait, continuing working on this.

Since @dpchoudhury2039 fixed the issue, and the fix is working, let us work on other issues now.
